### ISSUE TITLE
Jessie

### ISSUE THREAD

**Issue by LuckyLukeCH** [JamesHarrison/openob#30]
Hello James,

First thank you for you nice project; I appreciate it!

I was able to run successful a forward and backward link with 2 RPI2/3 and 2 UCA202. So the docs should be changed, that from RPI2 and up, the USB SoundCard could be used.

Now the question: Do you have any plans to port OpenOB to Jessie for RPI3? There are some minor changes in the packages. 

Thank you and regards from Switzerland
Lukas

**Comment by JamesHarrison** [comment]
Closing as 4.0 addresses this.
