### ISSUE TITLE
pcm mode not working

### ISSUE THREAD

**Issue by djsakisd** [JamesHarrison/openob#43]
Hi @JamesHarrison and @jonty-comp 

It seems that there is an issue with pcm audio and latest version.

I tried first with latest openob version (for Gst 1.0) and opus audio and all works fine.
With pcm audio it doesnt work at all, rx seems to get data but stuck and no audio is out.

After inserting an error trap inside on_message function while on pcm audio and run again i got this error from receiver `Error: gst-stream-error-quark: Internal data flow error. (1)`

When i tried this setup : tx (last version Gst 1.0) and rx (old version of openob gst 0.10 - i manually add caps in redis for old version cause there are not compatible between Gst 1.0 and Gst 0.10 ) then pcm works fine, so the problem might be on Receiver class.
By having a look in redis caps and in code everything seems fine for pcm audio though but i'm not very familiar with Gst code so i can't help further.

Could someone verify that pcm audio works with latest version and it's not a specific issue with jessie ?
All Gstreamer libraries for old and new version are installed with all the plugins also..

This issue happens on Raspbian jessie with python 2.7.

**Comment by jonty-comp** [comment]
This one is puzzling - I've just tested it on my local machine (Buster, Python 2.7) and PCM mode is working fine, but unfortunately I don't have a Pi set up that I can use as a receiver at the moment.

Can you confirm the version of your `gstreamer1.0-plugins-base` package?  The old openob uses an older GStreamer so it's possible it's a bug in GST itself.  We can dig deeper with `GST_DEBUG=3` before the openob command but that produces a huge mess of output that can be difficult to dig through.

**Comment by djsakisd** [comment]
Hi @jonty-comp 

You were right, after investigating gstreamer1.0-plugins-base was a bit old, if i remember correct it was 1.4.4-2, i tried to compile the latest gstreamer but it constantly fails to jessie, so i upgraded my jessie to stretch and issue is resolved at least on gstreamer 1.10.4 


Thanks for helping, im closing the issue .
