### ISSUE TITLE
Reddis auto reconnect

### ISSUE THREAD

**Issue by scottgrobinson** [JamesHarrison/openob#46]
Feature request!

If either the 'server' or 'client' are unable to connect to Redis, we should auto re-try. Maybe with exponential backoff or similar.

I've got two RPi's that I use as TX & RX units. Sometimes the TX doesn't connect to reddis on boot (Probably because network isn't ready and I'm only starting it with @reboot in crontab), but if the RX comes up before the TX (With TX hosting the 'server'), it needs a reboot to automatically connect.

**Comment by scottgrobinson** [comment]
https://github.com/JamesHarrison/openob/pull/47

**Comment by JamesHarrison** [comment]
Thanks for the fix! Merged and released.
